//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project5_voting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Debate
    {
        public long id { get; set; }
        public string electionArea { get; set; }
        public string firstCandidateName { get; set; }
        public string firstCandidateID { get; set; }
        public string firstCandidateList { get; set; }
        public string secondCandidateName { get; set; }
        public string secondCandidateID { get; set; }
        public string secondCandidateList { get; set; }
        public string debateSubject { get; set; }
        public string debateMessage { get; set; }
        public Nullable<System.DateTime> debateDate { get; set; }
        public Nullable<System.TimeSpan> debateTime { get; set; }
        public string zoomLink { get; set; }
        public string status { get; set; }
    }
}
