//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project5_voting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartyCandidate
    {
        public long id { get; set; }
        public Nullable<int> partyListID { get; set; }
        public string nastionalID { get; set; }
        public string name { get; set; }
        public string email { get; set; }
        public string typeOfChair { get; set; }
        public string religion { get; set; }
        public string gender { get; set; }
        public Nullable<System.DateTime> birthday { get; set; }
        public string candidateImage { get; set; }
        public string status { get; set; }
        public string electoralDistrict { get; set; }
    
        public virtual PartyList PartyList { get; set; }
    }
}
