//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project5_voting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER
    {
        public int id { get; set; }
        public string nationalID { get; set; }
        public string name { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public string gender { get; set; }
        public Nullable<System.DateTime> birthday { get; set; }
        public string religion { get; set; }
        public string placeOfResidence { get; set; }
        public string electionArea { get; set; }
        public string elctionLocation { get; set; }
        public Nullable<int> localVote { get; set; }
        public Nullable<int> partyVote { get; set; }
        public Nullable<int> whiteLocalVote { get; set; }
        public Nullable<int> whitePartyVote { get; set; }
    }
}
